services:
  - type: web
    name: bakone-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      bash render_start.sh
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
    staticPublishPath: staticfiles
